version: '3.8'

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8001:8080"
      -
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8080"
    depends_on:
      - auth
      - blockchain-processor
      - data-processor

  blockchain-processor:
    build:
      context: ./blockchain-processor
      dockerfile: Dockerfile
    container_name: blockchain-processor
    ports:
      - "8002:8080"

  data-processor:
    build:
      context: ./data-processor
      dockerfile: Dockerfile
    container_name: data-processor
    ports:
      - "8003:8080"